---
title: "microbialites_data"
output: html_document
date: "2023-12-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(DBI)
library(RMySQL)
```

## Insert Waypoint_ddl data

```{r cars}
waypoint <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblWaypointData.txt")

```

```{r}
names(waypoint)[2] = "WayptName"
names(waypoint)[1] = "OldWayptID"
waypoint$NewWayptID <- seq_along(waypoint$WayptName)
waypoint$WaypointSrc = NULL


Waypoint <- waypoint[, !names(waypoint) %in% c("Northing", "Easting")]
Coordinates <- waypoint[,c("OldWayptID","Latitude","Longitude","Northing", "Easting")]
```
##wypt data mapping
```{r}
waypoint_mapping <- Waypoint[, c("OldWayptID", "NewWayptID")]
```

```{r}
Waypoint <- merge(Waypoint, waypoint_mapping, by.x = "OldWayptID",by.y ="OldWayptID" )
Coordinates <- merge(Coordinates, waypoint_mapping, by.x = "OldWayptID",by.y ="OldWayptID" )
```

```{r}
Waypoint$OldWayptID = NULL
Waypoint$NewWayptID.y = NULL
```

```{r}
names(Waypoint)[18] = "WayptID"
```

```{r}
Coordinates$OldWayptID = NULL
```

```{r}
names(Coordinates)[5] = "WayptID"
```


```{r}
# MySQL connection parameters
dbname <- "microbialites"  
host <- "localhost"  
user <- "root" 
password <- "12344321"  

# Connect to MySQL database
con <- dbConnect(RMySQL::MySQL(), dbname = dbname, host = host, 
                 user = user, password = password)

# Delete existing rows in the Waypoint table without dropping the table
dbExecute(con, "DELETE FROM Waypoint")
dbExecute(con,"DELETE FROM Coordinates")
# Write the dataframe to MySQL without dropping/recreating the table
dbWriteTable(con, "Waypoint", Waypoint, append = TRUE, row.names = FALSE)
dbWriteTable(con, "Coordinates", Coordinates, append = TRUE, row.names = FALSE)

# Close the connection
dbDisconnect(con)

```
##Insert macroStructure_ddl data

```{r cars}
 #AspectRatio <- 
 meso <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblAllMesostructures.txt")
 macro <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblMacrostructureData.txt")
 
```
#MacroStructure
```{r}
names(macro)[1] = "OldMacroStructureID"
names(macro)[4] = "OldWayptID"
macro$NewMacroStructureID <- seq_along(macro$OldMacroStructureID)
MacroStructure <- macro[,c("NewMacroStructureID","OldMacroStructureID","OldWayptID")]
```
#Macro Data mapping
```{r}
macroStructure_mapping <-macro[,c("NewMacroStructureID","OldMacroStructureID")]

```

```{r}
MacroStructure <- merge(MacroStructure, waypoint_mapping, by.x = "OldWayptID",by.y ="OldWayptID" )
MacroStructure <- MacroStructure[,c("NewWayptID","OldMacroStructureID","NewMacroStructureID")]
MacroStructure <- merge(MacroStructure,macroStructure_mapping,by.x = "OldMacroStructureID",by.y= "OldMacroStructureID")
MacroStructure <- MacroStructure[,2:3]
names(MacroStructure)[2] = "MacroStructureID"
names(MacroStructure)[1] = "WayptID"
```
#MacroStructurePhotos
```{r}
PhotoLinks <-  read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblPhotoLinksData.txt")
# Filter out rows where MacrostructureID or WayptIDKey is NA or less than 2
df_photo <- PhotoLinks[!is.na(PhotoLinks$MacrostructureID) & PhotoLinks$MacrostructureID >= 2, ]
df_photo <- df_photo[!is.na(df_photo$WayptIDKey) & df_photo$WayptIDKey >= 2, ]

```

```{r}
df_photo$NewPhotoID <- seq_along(df_photo$keyPhotoID)
photoID_mapping <- df_photo[,c("keyPhotoID","NewPhotoID")]
```

```{r}
names(df_photo)[3] = "OldMacroStructureID"
df_photo <- merge(df_photo, macroStructure_mapping, by.x ="OldMacroStructureID",by.y ="OldMacroStructureID" )
```

```{r}
df_photo <- merge(df_photo, waypoint_mapping, by.x = "WayptIDKey", by.y = "OldWayptID")
```

```{r}
df_photo <- merge(df_photo,photoID_mapping,by.x="keyPhotoID",by.y="keyPhotoID")
```

```{r}
MacroStructurePhotos <- df_photo[,c("NewMacroStructureID","NewPhotoID.y","NewWayptID","InReport","OutcropPhoto","Photomicrograph","OtherImage","CLImage","OtherDocument","PhotoLinkRelative2")]
```

```{r}
names(MacroStructurePhotos)[1] = "MacroStructureID"
names(MacroStructurePhotos)[2] = "PhotoID"
names(MacroStructurePhotos)[3] = "WayptID"
names(MacroStructurePhotos)[10] = "ReferenceLink"
```



```{r}

# MySQL connection parameters
dbname <- "microbialites"  # The name of your database
host <- "localhost"  # Since the user 'root' has access from 'localhost'
user <- "root"  # The username indicated in MySQL Workbench
password <- "12344321"  # The password you have for the 'root' user

# Connect to your MySQL database
con <- dbConnect(RMySQL::MySQL(), dbname = dbname, host = host, 
                 user = user, password = password)


# Write the dataframe to MySQL without dropping/recreating the table
dbWriteTable(con, "MacroStructure", MacroStructure, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MacroStructurePhotos", MacroStructurePhotos, append = TRUE, row.names = FALSE)

# Close the connection
dbDisconnect(con) 

```

# MacroStructureProperties
```{r}
MegaStructureType <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblMegastructureTypes.txt") 
MegaStructureShape <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblMegastructureTypes.txt") 
MegaStructureSize <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblMegastructureTypes.txt") 
Substrate <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpSubstrate.txt") 
PlainView <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpPlanView.txt")
Linkage <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpLinkage.txt")
Initiation <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpInitiation.txt")
Spacing <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpSpacing.txt")
Shape <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpShape.txt")
ShapeLayering <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpLayerShape.txt")
ColumnShape <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpColumnShape.txt")
ShapeDome <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpShape.txt")
ConicalShape <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpConicalShapes.txt")
Attitude <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpAttitude.txt")
BranchingStyle <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpBranchingStyle.txt")
AspectRatio <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpAspectRatio.txt")
GrowthVariability <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpGrowthVariability.txt")
BranchingMode <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpBranchingMode.txt")
BranchingAngle <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpDivergenceAngle.txt")
MacroStructureTypes <-   read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblMacrostructureTypes.txt")
```

```{r}
names(MegaStructureType)[1] =  "TypeID"
names(MegaStructureShape)[1] = "ShapeID"
names(MegaStructureSize)[1] =  "SizeID"
names(Substrate)[1] =          "SubstrateID"
names(Substrate)[2] =          "SubstrateName"
names(PlainView)[1] =          "PlanViewID"
names(PlainView)[2] =          "PlanViewName"
names(Linkage)[1]   =  "LinkageID"
names(Linkage)[2]   =  "LinkageName"
names(Initiation)[1] = "InitiationID"
names(Initiation)[2] = "InitiationName"
names(Spacing)[1] = "SpacingID"
names(Spacing)[2] = "SpacingName"
names(Shape)[1] = "ShapeID"
names(Shape)[2] = "ShapeName"
names(ShapeLayering)[1] = "ShapeLayeringID"
names(ShapeLayering)[2] = "ShapeLayeringName"
names(ColumnShape)[1] = "ColumnShapeID"
names(ColumnShape)[2] = "ColumnShapeName"
names(ShapeDome)[1] = "ShapeDomeID"
names(ShapeDome)[2] = "ShapeDomeName"
names(ConicalShape)[1] = "ConicalShapeID"
names(ConicalShape)[2] = "ConicalShapeName"
names(Attitude)[1] = "AttitudeID"
names(Attitude)[2] = "AttitudeName"
names(BranchingStyle)[1] = "BranchingStyleID"
names(BranchingStyle)[2] = "BranchingStyleName"
names(AspectRatio)[1] = "AspectRatioID"
names(AspectRatio)[2] = "AspectRatioName"
names(GrowthVariability)[1] = "GrowthVariabilityID"
names(GrowthVariability)[2] = "GrowthVariabilityName"
names(BranchingMode)[1] = "BranchingModeID"
names(BranchingMode)[2] = "BranchingModeName"
names(BranchingAngle)[1] = "BranchingAngleID"
names(BranchingAngle)[2] = "BranchingAngleName"

```

```{r}
MacroStructureTypes <- MacroStructureTypes[1:3]
MacroStructureTypes$MacroStructureTypesID <- seq_along(MacroStructureTypes$ID)
```


```{r}
macroType_mapping <- MacroStructureTypes[,c("ID","MacroStructureTypesID")]
```

```{r}
MacroStructureTypes <- MacroStructureTypes[2:4]
```



```{r}
# MySQL connection parameters
dbname <- "microbialites"  # The name of your database
host <- "localhost"  # Since the user 'root' has access from 'localhost'
user <- "root"  # The username indicated in MySQL Workbench
password <- "12344321"  # The password you have for the 'root' user

# Connect to your MySQL database
con <- dbConnect(RMySQL::MySQL(), dbname = dbname, host = host, 
                 user = user, password = password)


# Write the dataframe to MySQL without dropping/recreating the table
#dbWriteTable(con, "MegaStructureType", MegaStructureType, append = TRUE, row.names = FALSE)
#dbWriteTable(con, "MegaStructureShape", MegaStructureShape, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MegaStructureSize", MegaStructureSize, append = TRUE, row.names = FALSE)
dbWriteTable(con, "Substrate", Substrate, append = TRUE, row.names = FALSE)
dbWriteTable(con, "PlainView", PlainView, append = TRUE, row.names = FALSE)
dbWriteTable(con, "Linkage", Linkage, append = TRUE, row.names = FALSE)
dbWriteTable(con, "Initiation",Initiation, append = TRUE, row.names = FALSE)
dbWriteTable(con, "Spacing",Spacing, append = TRUE, row.names = FALSE)
dbWriteTable(con, "Shape",Shape, append = TRUE, row.names = FALSE)
dbWriteTable(con, "ShapeLayering",ShapeLayering, append = TRUE, row.names = FALSE)
dbWriteTable(con, "ColumnShape",ColumnShape, append = TRUE, row.names = FALSE)
dbWriteTable(con, "ShapeDome",ShapeDome, append = TRUE, row.names = FALSE)
dbWriteTable(con, "ConicalShape",ConicalShape, append = TRUE, row.names = FALSE)
dbWriteTable(con, "Attitude",Attitude, append = TRUE, row.names = FALSE)
dbWriteTable(con, "BranchingStyle",BranchingStyle, append = TRUE, row.names = FALSE)
dbWriteTable(con, "AspectRatio",AspectRatio, append = TRUE, row.names = FALSE)
dbWriteTable(con, "GrowthVariability",GrowthVariability, append = TRUE, row.names = FALSE)
dbWriteTable(con, "BranchingMode",BranchingMode, append = TRUE, row.names = FALSE)
dbWriteTable(con, "BranchingAngle",BranchingAngle, append = TRUE, row.names = FALSE)
dbWriteTable(con, "ColumnShape",ColumnShape, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MacroStructureTypes",MacroStructureTypes, append = TRUE, row.names = FALSE)
# Close the connection
dbDisconnect(con) 
```
```{r}
MacroStructureProperties <- macro
```

```{r}
names(MacroStructureProperties)[2] = "OldMacrostructureTypeID"
```


```{r}
names(MacroStructureProperties)[6] = "MegaStructureTypeID"
names(MacroStructureProperties)[7] = "MegastructureShapeID"
names(MacroStructureProperties)[8] = "MegaStructureSizeID"
names(MacroStructureProperties)[9] = "SubstrateID"
names(MacroStructureProperties)[10] = "InitiationID"
names(MacroStructureProperties)[11] = "PlanViewID"
names(MacroStructureProperties)[12] = "LinkageID"
names(MacroStructureProperties)[13] = "SpacingID"
names(MacroStructureProperties)[14] = "ShapeID"
names(MacroStructureProperties)[15] = "ShapeLayeringID"
names(MacroStructureProperties)[16] = "ShapeDomeID"
names(MacroStructureProperties)[17] = "ConicalShapeID"
names(MacroStructureProperties)[18] = "AspectRatioID"
names(MacroStructureProperties)[19] = "GrowthVariabilityID"
names(MacroStructureProperties)[20] = "AttitudeID"
names(MacroStructureProperties)[21] = "BranchingStyleID"
names(MacroStructureProperties)[22] = "BranchingModeID"
names(MacroStructureProperties)[23] = "BranchingAngleID"
names(MacroStructureProperties)[24] = "ColumnShapeID"
```

```{r}
MacroStructureProperties <- merge(MacroStructureProperties,macroType_mapping , by.x ="OldMacrostructureTypeID",by.y ="ID" )
```

```{r}
MacroStructureProperties <- merge(MacroStructureProperties,waypoint_mapping , by.x ="OldWayptID",by.y ="OldWayptID" )
```

```{r}
MacroStructureProperties$OldWayptID = NULL
MacroStructureProperties$OldMacroStructureID = NULL
MacroStructureProperties$OldMacrostructureTypeID = NULL
```

```{r}
names(MacroStructureProperties)[22] = "MacrostructureID"
MacroStructureProperties$NewWayptID = NULL #accidentally merged it  
```

```{r}
# MySQL connection parameters
dbname <- "microbialites"  # The name of your database
host <- "localhost"  # Since the user 'root' has access from 'localhost'
user <- "root"  # The username indicated in MySQL Workbench
password <- "12344321"  # The password you have for the 'root' user

# Connect to your MySQL database
con <- dbConnect(RMySQL::MySQL(), dbname = dbname, host = host, 
                 user = user, password = password)


# Write the dataframe to MySQL without dropping/recreating the table
dbWriteTable(con, "MacroStructureProperties",MacroStructureProperties, append = TRUE, row.names = FALSE)
# Close the connection
dbDisconnect(con) 
```
##Insert MesoStructure data

##Insert MesoStructure data

```{r}
meso <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblAllMesostructures.txt")
```

```{r}
meso_data <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblMesostructureData.txt")
```


```{r}
meso_data <- meso_data[-243,] #removed the only duplicate SampleID "17-WB-1b" there were conflicting records
```


```{r}
meso_data$SampleIDKey = NULL
meso_data$WayptName = NULL
```


```{r}
names(meso_data)[10] = "OldMacroStructureID"

```

```{r}
meso_data <- merge(meso_data,macroStructure_mapping,by = "OldMacroStructureID",all.x = TRUE)
```

```{r}
names(meso_data)[49] = "MacroStructureID"
meso_data$OldMacroStructureID = NULL
```

```{r}
meso_data <- merge(meso_data,MacroStructure,by = "MacroStructureID",all.x = TRUE)
```


```{r}
meso_data$MesoStructureID <- seq_along(meso_data$SampleID)
```

```{r}
MesoStructure <- meso_data[,c("MesoStructureID","MacroStructureID","WayptID","SampleID")]
names(MesoStructure)[4] = "MesoStructureName"
```

```{r}
MesoStructure$MesoStructureName = NULL
```


```{r}
df_photo_meso <- PhotoLinks[!(is.na(PhotoLinks$SampleID) | PhotoLinks$SampleID == 0), ]
df_photo_meso <- df_photo[!(is.na(df_photo$SampleIDKey) | df_photo$SampleIDKey == 0), ]
```

```{r}
names(df_photo_meso)[4] = "MesoStructureName"
```

```{r}
mesoName_to_ID <- MesoStructure[,c("MesoStructureName","MesoStructureID")]
```

```{r}
MesoStructureSampleName <- mesoName_to_ID
```

```{r}
df_photo_meso <- merge(df_photo_meso, mesoName_to_ID, by = "MesoStructureName", all.x = TRUE )
```


```{r}
df_photo_meso$PhotoID = NULL
df_photo_meso$PhotoID <- seq_along(df_photo_meso$keyPhotoID)
```

```{r}
MesoStructurePhotos <- df_photo_meso[,c("MesoStructureID","PhotoID","NewWayptID","NewMacroStructureID","PhotoLinkRelative2","InReport","OutcropPhoto","Photomicrograph","OtherImage","CLImage","OtherDocument")]
```

```{r}
names(MesoStructurePhotos)[3] = "WayptID" 
names(MesoStructurePhotos)[4] = "MacroStructureID" 
names(MesoStructurePhotos)[5] = "RefrenceLink"
```

```{r}
InternationalSampleNumber <- meso_data[,c("MesoStructureID","IGSNIntlGeoSampleNumber")]
```

```{r}
InternationalSampleNumber <- InternationalSampleNumber[!(InternationalSampleNumber$IGSNIntlGeoSampleNumber == ""),]
```

```{r}
TextureType <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblMesostructureTextureTypes.txt")
TextureType$SortOrder = NULL
names(TextureType)[1] = "TextureTypeID"
names(TextureType)[2] = "MesoStructureTextureType"
```

```{r}
names(MesoTextureTypes)
```


```{r}
tblTextureTypes <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblTextureTypes.txt")
```




```{r}
MesoTextureTypes$SortOrder = NULL
```

```{r}
MesoStructureTextureTypes <- meso_data[,c("MesoStructureID","MesostructureTexture2","MesostructureTexture")]
```

```{r}
MesoStructureTextureTypes <- MesoStructureTextureTypes[!(is.na(MesoStructureTextureTypes$MesostructureTexture2) | MesoStructureTextureTypes$MesostructureTexture2 > 13),]
MesoStructureTextureTypes <- MesoStructureTextureTypes[!(is.na(MesoStructureTextureTypes$MesostructureTexture) | MesoStructureTextureTypes$MesostructureTexture > 13),]
```

```{r}
temp1 <- MesoStructureTextureTypes[, c("MesoStructureID", "MesostructureTexture")]
temp2 <- MesoStructureTextureTypes[, c("MesoStructureID", "MesostructureTexture2")]

# Rename the texture columns in both data frames to have the same name
names(temp1)[2] <- "TextureTypeID"
names(temp2)[2] <- "TextureTypeID"

# Combine the two data frames
combined <- rbind(temp1, temp2)
```

```{r}
MesoStructureTextureTypes <- combined
```

```{r}
Architecture <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoArchitecture.txt")
names(Architecture)[1] = "ArchitectureID"
names(Architecture)[2] = "ArchitectureType"
```

```{r}
MesoGrainType <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblMesostructureGrainTypes.txt")
names(MesoGrainType)[1] = "GrainTypeID"
names(MesoGrainType)[2] = "GrainType"
```

```{r}
MesoGrainType$SortOrder = NULL
```

```{r}
ThinSectionPriority <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblThinSectionPriority.txt")
MesoInheritance <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoInheritance.txt")
MesoStructureType <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblMesostructureTypes.txt")
MesoStructureLaminaPattern <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoLaminarPattern.txt")
MesoStackingOverlap <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoStackingOverlap.txt")
MesoAlternation <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoAlternation.txt")
MesoWaviness <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoWaviness.txt")
MesoModalitySkewness <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoModalitySkewness.txt")
MesoLaminaProfile <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoLamProfile.txt")
MesoSynopticRelief <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoSynopticRelief.txt")
MesoLaminaIneritance <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblLaminaInheritance.txt")
MesoLateralContinuity <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoLatContinuity.txt")
MesoWalls <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoWalls.txt")
MesoMacroLaminae <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoMacrolaminae.txt")
MesoLaminaShape <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblLaminaShapeTypes.txt")
MesoClotType <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblMesoClotTypes.txt")
MesoClotShape <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tlkpMesoClotShape.txt")
  
```

```{r}
ThinSectionPriority$SortOrder = NULL
names(ThinSectionPriority)[1] = "ThinSectionPriorityID"
names(ThinSectionPriority)[2] = "PriorityType"
```

```{r}
names(MesoInheritance)[1] = "MesoInheritanceID"
names(MesoInheritance[2]) = "Inheritance"
```

```{r}
MesoStructureType$SortOrder = NULL
names(MesoStructureType)[1] = "MesoStructureTypeID"
```

```{r}
names(MesoStructureLaminaPattern)[1] = "MesoStructureLaminaPatternID"
```

```{r}
names(MesoStackingOverlap)[1] = "MesoStackingOverlapID"
```

```{r}
names(MesoAlternation)[1] = "MesoAlterationID"
```

```{r}
names(MesoWaviness)[1] = "MesoWavinessID"
```

```{r}
names(MesoModalitySkewness)[1] = "MesoModalityID"
```

```{r}
names(MesoLaminaProfile)[1] = "MesoLaminaProfileID"
```

```{r}
names(MesoSynopticRelief)[1] = "MesoSynopticReliefID"
```

```{r}
MesoLaminaIneritance$Sort = NULL
names(MesoLaminaIneritance)[1] = "MesoLaminaInheritanceID"
names(MesoLaminaIneritance)[2] = "Inheritance"

```

```{r}
names(MesoLateralContinuity)[1] = "MesoLateralContinuityID"
names(MesoLateralContinuity)[2] = "LateralContinuity"
```

```{r}
names(MesoWalls)[1] = "MesoWallsID"
names(MesoWalls)[2] = "Walls"
```

```{r}
names(MesoMacroLaminae)[1] = "MesoMacroLaminaeID"
names(MesoMacroLaminae)[2] = "MacroLaminae"
```

```{r}
names(MesoLaminaShape)[1] = "MesoLaminaShapeID"
names(MesoLaminaShape)[2] = "LaminaShape"
```

```{r}
MesoLaminaShape$Sort = NULL
```

```{r}
names(MesoClotType)[1] = "MesoClotTypeID"
names(MesoClotType)[2] = "ClotType"
MesoClotType$Sort = NULL
```

```{r}
names(MesoClotShape)[1] = "MesoClotShapeID"
names(MesoClotShape)[2] = "ClotShape"
```

```{r}
MesoStructureProperties <- meso_data[,c("MesoStructureID","MesostructureGrains","ThinSectionPriority","Inheritance","MesostructureType","LaminaePatterns","StackingOverlap","Alternation","Waviness","Modality","LaminaProfile","LaminaThickness","SynopticReliefNew","Lamina.Inheritance","LaterialContinuity","Wall","MacroLaminae","LaminaShape","MesostructureType","MesoCLotShape","MesoClotSize","InTheFRUInterval","AnalysisPriority","MacroStructureID","FieldDescription","Lithology","RockDescription","SampleSize","PeelAndSEMPriority","ThinSectionMade","C_N_Priority","Wavelength","AmplitudeOrHeight","MicrobialiteType","BriefNotes")]
```

```{r}
MesoStructureProperties$MesoClotTypeID <- NA
```

```{r}
names(MesoStructureProperties)[2] = "GrainTypeID"
names(MesoStructureProperties)[3] = "ThinSectionPriorityID"
names(MesoStructureProperties)[4] = "MesoInhertianceID"
names(MesoStructureProperties)[5] = "MesoStructureTypeID"
names(MesoStructureProperties)[6] = "MesoStructureLaminaPatternID"
names(MesoStructureProperties)[7] = "MesoStackingOverlapID"
names(MesoStructureProperties)[8] = "MesoAlterationID"
names(MesoStructureProperties)[9] = "MesoWavinessID"
names(MesoStructureProperties)[10] = "MesoModailityID"
names(MesoStructureProperties)[11] = "MesoLaminaProfileID"
names(MesoStructureProperties)[13] = "MesoSynopticReliefID"
names(MesoStructureProperties)[14] = "MesoLaminaInhertianceID"
names(MesoStructureProperties)[15] = "MesoLateralContinuityID"
names(MesoStructureProperties)[16] = "MesoWallsID"
names(MesoStructureProperties)[17] = "MesoMacroLaminaeID"
names(MesoStructureProperties)[18] = "MesoLaminaShapeID"
names(MesoStructureProperties)[19] = "MesoStructureTypeID"
names(MesoStructureProperties)[20] = "MesoClotShapeID"
names(MesoStructureProperties)[21] = "MesoClotSizeID"
```

```{r}
MesoStructureProperties$MesoStructureTypeID.1 = NULL
```

```{r}
# MySQL connection parameters
dbname <- "microbialites"  # The name of your database
host <- "localhost"  # Since the user 'root' has access from 'localhost'
user <- "root"  # The username indicated in MySQL Workbench
password <- "12344321"  # The password you have for the 'root' user

# Connect to your MySQL database
con <- dbConnect(RMySQL::MySQL(), dbname = dbname, host = host, 
                 user = user, password = password)


# Write the dataframe to MySQL without dropping/recreating the table

dbWriteTable(con, "MesoStructure",MesoStructure, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoStructure",MesoStructure, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoStructurePhotos",MesoStructurePhotos, append = TRUE, row.names = FALSE)
dbWriteTable(con, "InternationalSampleNumber",InternationalSampleNumber, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoStructureSampleName",MesoStructureSampleName, append = TRUE, row.names = FALSE)
dbWriteTable(con, "TextureType",TextureType, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoStructureTextureTypes",MesoStructureTextureTypes, append = TRUE, row.names = FALSE)
dbWriteTable(con, "Architecture", Architecture, append = TRUE, row.names = FALSE)
#dbWriteTable(con, "MesoStructureArchitecture",MesoStructureArchitecture, append = TRUE, row.names = FALSE) did not need to run as there is no data rn
dbWriteTable(con, "MesoGrainType",MesoGrainType, append = TRUE, row.names = FALSE)
dbWriteTable(con, "ThinSectionPriority",ThinSectionPriority, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoInheritance",MesoInheritance, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoStructureType",MesoStructureType, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoStructureLaminaPattern",MesoStructureLaminaPattern, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoStackingOverlap",MesoStackingOverlap, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoAlternation",MesoAlternation, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoWaviness", MesoWaviness, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoModalitySkewness",MesoModalitySkewness, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoSynopticRelief",MesoSynopticRelief, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoLaminaInheritance",MesoLaminaInheritance, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoLateralContinuity",MesoLateralContinuity, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoWalls",MesoWalls, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoMacroLaminae",MesoMacroLaminae, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoLaminaShape",MesoLaminaShape, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoClotType",MesoClotType, append = TRUE, row.names = FALSE)
dbWriteTable(con, "MesoClotShape",MesoClotShape, append = TRUE, row.names = FALSE)
dbWriteTable(con, "Priority",Priority, append = TRUE, row.names = FALSE)

# Close the connection
dbDisconnect(con) 
```

```{r}
MesoLaminaInheritance <- MesoLaminaIneritance
```

```{r}
names(MesoLateralContinuity)[1] = "MesoLateralContinuityID"
names(MesoLateralContinuity)[2] = "LateralContinuity"
```

```{r}
names(MesoStructureProperties)[14] = "MesoLaminaInheritanceID"
```

```{r}
names(MesoStructureProperties)[4] = "MesoInheritanceID"
```

```{r}
names(MesoStructureProperties)[10] = "MesoModalityID"
```

```{r}
names(MesoStructureProperties)[16] = "MesoWallsID"
```

```{r}
names(MesoStructureProperties)[21] = "MesoClotSize"
```


```{r}
Priority <- data.frame(c(1:3), c("Low","Medium","High"))
names(Priority)[1] = "ID"
names(Priority)[2] = "Priority"
```

```{r}

MesoStructureProperties[,19] = NULL

```


```{r}
# MySQL connection parameters
dbname <- "microbialites"  # The name of your database
host <- "localhost"  # Since the user 'root' has access from 'localhost'
user <- "root"  # The username indicated in MySQL Workbench
password <- "12344321"  # The password you have for the 'root' user

# Connect to your MySQL database
con <- dbConnect(RMySQL::MySQL(), dbname = dbname, host = host, 
                 user = user, password = password)

# Write the dataframe to MySQL without dropping/recreating the table


dbWriteTable(con, "MesoStructureProperties",MesoStructureProperties, append = TRUE, row.names = FALSE)

# Close the connection
dbDisconnect(con) 
```

```{r}
unique_links <- unique(PhotoLinks$PhotoLinkRelative2)
```

```{r}
photos <- data.frame(PhotoID = seq_along(unique_links), PhotoLinkName = unique_links)
```

```{r}
photos <- photos[-c(1694),] #removed an entry emoty for photo link
```


```{r}
macrostructurephotos <- MacroStructurePhotos

```

```{r}
macrostructurephotos$PhotoID = NULL
macrostructurephotos <- merge(macrostructurephotos, photos, by.x = "ReferenceLink",by.y = "PhotoLinkName", all.x = TRUE )
```

```{r}
mesostructurephotos <- MesoStructurePhotos
mesostructurephotos$PhotoID = NULL
names(mesostructurephotos)[4] = "ReferenceLink"

```


```{r}
mesostructurephotos <- merge(mesostructurephotos, photos, by.x = "ReferenceLink",by.y = "PhotoLinkName", all.x = TRUE )
```


```{r}
# MySQL connection parameters
dbname <- "h762lahe056bge13"  
host <- "nnsgluut5mye50or.cbetxkdyhwsb.us-east-1.rds.amazonaws.com"  
user <- "izgrmlgwk70csp9l"  
password <- "qpmikh9t3n3a2ekg" 

# Connect to your MySQL database
con <- dbConnect(RMySQL::MySQL(), dbname = dbname, host = host, 
                 user = user, password = password)

# Write the dataframe to MySQL without dropping/recreating the table
dbExecute(con, "DELETE FROM mesostructurephotos")
dbExecute(con,"DELETE FROM macrostructurephotos")

dbWriteTable(con, "photos",photos, append = TRUE, row.names = FALSE)
dbWriteTable(con, "macrostructurephotos",macrostructurephotos, append = TRUE, row.names = FALSE)
dbWriteTable(con, "mesostructurephotos",mesostructurephotos, append = TRUE, row.names = FALSE)

# Close the connection
dbDisconnect(con) 
```

```{r}
# MySQL connection parameters
dbname <- "h762lahe056bge13"  
host <- "nnsgluut5mye50or.cbetxkdyhwsb.us-east-1.rds.amazonaws.com"  
user <- "izgrmlgwk70csp9l"  
password <- "qpmikh9t3n3a2ekg" 

# Connect to your MySQL database
con <- dbConnect(RMySQL::MySQL(), dbname = dbname, host = host, 
                 user = user, password = password)

dbExecute(con, "DELETE FROM photos")
dbWriteTable(con, "photos",photos, append = TRUE, row.names = FALSE)


# Close the connection
dbDisconnect(con) 
```

```{r}
tblThinSectionDescriptionData <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblThinSectionDescriptionData.txt")
```

```{r}
tblThinSectionDescriptionData  <- merge(tblThinSectionDescriptionData,mesoName_to_ID,by.x = "SampleID",by.y = "MesoStructureName" )

```

```{r}
#missing_sampleIDs <- tblThinSectionDescriptionData[is.na(tblThinSectionDescriptionData$MesoStructureID),]
```

```{r}
#missing_sampleIDs <- missing_sampleIDs$SampleID
```



```{r}
meso_to_macro <- meso_data[,c("MesoStructureID","MacroStructureID")]
```

```{r}
tblThinSectionDescriptionData  <- merge(tblThinSectionDescriptionData,meso_to_macro,by = "MesoStructureID" )
```

```{r}
tblThinSectionDescriptionData  <- merge(tblThinSectionDescriptionData,MacroStructure,by = "MacroStructureID" )
```

```{r}
tblThinSectionDescriptionData$ThinStructureID <- seq_along(tblThinSectionDescriptionData$TSDescription)
```

```{r}
thin_to_id <- tblThinSectionDescriptionData[,c("ThinStructureID","TSDescID")]
```


```{r}
ThinStructures <- tblThinSectionDescriptionData[,c("WayptID","MacroStructureID","MesoStructureID","ThinStructureID")]
```

```{r}
df_photo_thin <- df_photo[!is.na(df_photo$TSDescID) & df_photo$TSDescID >= 6, ]

```

```{r}
df_photo_thin <- df_photo_thin[!is.na(df_photo_thin$SampleID) & !df_photo_thin$SampleID == "", ]
```

```{r}
df_photo_thin$NewPhotoID.x = NULL
df_photo_thin$NewPhotoID.y = NULL
```

```{r}
ThinStructurePhotos <- df_photo_thin[,c("TSDescID","InReport","OutcropPhoto","Photomicrograph","OtherImage","CLImage" ,"OtherDocument","PhotoLinkRelative2")]
```

```{r}
ThinStructurePhotos  <- merge(ThinStructurePhotos,thin_to_id,by = "TSDescID")
```

```{r}
names(ThinStructurePhotos)[8] = "ReferenceLink"
ThinStructurePhotos$TSDescID = NULL
ThinStructurePhotos <- merge(ThinStructurePhotos, photos, by.x = "ReferenceLink",by.y = "PhotoLinkName", all.x = TRUE )
```

```{r}
ThinStructureProperties <- tblThinSectionDescriptionData[,c("PorosityPercentEst","CementFilledPorosity","ThinStructureID")]
```

```{r}
ThinTextureTypes <- tblTextureTypes[,1:2]
names(ThinTextureTypes)[1] = "ThinTextureTypeID"
ThinTextureTypes$ThinTextureTypeID <- seq_along(ThinTextureTypes$Texture)
names(ThinTextureTypes)[2] = "Texture"
# no need to map because thinData table does not ref textures past 7
```


```{r}
temp1 <- tblThinSectionDescriptionData[, c("ThinStructureID", "PrimaryTexture")]
temp2 <- tblThinSectionDescriptionData[, c("ThinStructureID", "SecondaryTexture")]

# Rename the texture columns in both data frames to have the same name
names(temp1)[2] <- "ThinTextureTypeID"
names(temp2)[2] <- "ThinTextureTypeID"

# Combine the two data frames
combined <- rbind(temp1, temp2)
```

```{r}
ThinStructureTextureTypes <- combined
ThinStructureTextureTypes <- ThinStructureTextureTypes[!is.na(ThinStructureTextureTypes$ThinTextureTypeID),]
```

```{r}
tblClasticGrainTypes <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblClasticGrainTypes.txt")
```

```{r}
ClasticGrains <- tblClasticGrainTypes[,1:2]
names(ClasticGrains)[1] = "ClasticGrainsID"
names(ThinTextureTypes)[2] = "ClasticGrainType"
```

```{r}
temp1 <- tblThinSectionDescriptionData[, c("ThinStructureID", "ClasticGrains1")]
temp2 <- tblThinSectionDescriptionData[, c("ThinStructureID", "ClasticGrains2")]

# Rename the texture columns in both data frames to have the same name
names(temp1)[2] <- "ClasticGrainsID"
names(temp2)[2] <- "ClasticGrainsID"

# Combine the two data frames
combined <- rbind(temp1, temp2)
```

```{r}
ThinStructureClasticGrains <- combined
```

```{r}
ThinStructureClasticGrains <- ThinStructureClasticGrains[!is.na(ThinStructureClasticGrains$ClasticGrainsID),]
```


```{r}
dbWriteTable(con, "thinstructures",ThinStructures, append = TRUE, row.names = FALSE)
dbWriteTable(con, "thinstructurephotos",ThinStructurePhotos, append = TRUE, row.names = FALSE)
dbWriteTable(con, "thinstructureproperties",ThinStructureProperties, append = TRUE, row.names = FALSE)
```


```{r}
# MySQL connection parameters
dbname <- "h762lahe056bge13"  
host <- "nnsgluut5mye50or.cbetxkdyhwsb.us-east-1.rds.amazonaws.com"  
user <- "izgrmlgwk70csp9l"  
password <- "qpmikh9t3n3a2ekg" 

# Connect to your MySQL database
con <- dbConnect(RMySQL::MySQL(), dbname = dbname, host = host, 
                 user = user, password = password)

#dbExecute(con, "DELETE FROM photos")


dbWriteTable(con, "thinstructuretexturetypes",ThinStructureTextureTypes, append = TRUE, row.names = FALSE)
dbWriteTable(con, "clasticgrains",ClasticGrains, append = TRUE, row.names = FALSE)
dbWriteTable(con, "thinstructureclasticgrains",ThinStructureClasticGrains, append = TRUE, row.names = FALSE)

# Close the connection
dbDisconnect(con) 
```

```{r}
tblCementTypes <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblCementTypes.txt")
```

```{r}
CementTypes <- tblCementTypes[,1:3]
names(CementTypes)[1] = "CementTypeID"
names(CementTypes)[2] = "Cement"
names(CementTypes)[3] = "CementDesc"
```

```{r}
temp1 <- tblThinSectionDescriptionData[, c("ThinStructureID", "Cement1")]
temp2 <- tblThinSectionDescriptionData[, c("ThinStructureID", "Cement2")]

# Rename the texture columns in both data frames to have the same name
names(temp1)[2] <- "CementTypeID"
names(temp2)[2] <- "CementTypeID"

# Combine the two data frames
combined <- rbind(temp1, temp2)
```

```{r}
ThinStructureCementTypes <- combined
```

```{r}
ThinStructureCementTypes <- ThinStructureCementTypes[!is.na(ThinStructureCementTypes$CementTypeID),]
```

```{r}
tblMineralogyTypes <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblMineralogyTypes.txt")
```

```{r}
MineralogyTypes <- tblMineralogyTypes
names(MineralogyTypes)[1] = "MineralogyID"
names(MineralogyTypes)[2] = "Mineralogy"
names(MineralogyTypes)[3] = "MineralogyDesc"

```


```{r}
tblPorosityTypes <- read.csv("~/Desktop/microbialites/Microbialites Access Tables CSV/tblPorosityTypes.txt")
```

```{r}
PorosityType <- tblPorosityTypes
names(PorosityType)[1] = "PorosityTypeID"
names(PorosityType)[2] = "PorosityType"
PorosityType$Sort = NULL
```

```{r}
temp1 <- tblThinSectionDescriptionData[, c("ThinStructureID", "Mineralogy1")]
temp2 <- tblThinSectionDescriptionData[, c("ThinStructureID", "Mineralogy2")]

# Rename the texture columns in both data frames to have the same name
names(temp1)[2] <- "MineralogyID"
names(temp2)[2] <- "MineralogyID"

# Combine the two data frames
combined <- rbind(temp1, temp2)
```

```{r}
ThinStructureMineralogyTypes <- combined
ThinStructureMineralogyTypes <- ThinStructureMineralogyTypes[!is.na(ThinStructureMineralogyTypes$MineralogyID),]
```

```{r}
temp1 <- tblThinSectionDescriptionData[, c("ThinStructureID", "Porosity1")]
temp2 <- tblThinSectionDescriptionData[, c("ThinStructureID", "Porosity2")]

# Rename the texture columns in both data frames to have the same name
names(temp1)[2] <- "PorosityTypeID"
names(temp2)[2] <- "PorosityTypeID"

# Combine the two data frames
combined <- rbind(temp1, temp2)
```

```{r}
ThinStructurePorosityType <- combined
ThinStructurePorosityType <- ThinStructurePorosityType[!is.na(ThinStructurePorosityType$PorosityTypeID),]
```

```{r}
names(MineralogyTypes)[3] = "MineralDesc"
```

```{r}
names(PorosityType)[2] = "Porosity"
PorosityType$Sort = NULL
```


```{r}
# MySQL connection parameters
dbname <- "h762lahe056bge13"  
host <- "nnsgluut5mye50or.cbetxkdyhwsb.us-east-1.rds.amazonaws.com"  
user <- "izgrmlgwk70csp9l"  
password <- "qpmikh9t3n3a2ekg" 

# Connect to your MySQL database
con <- dbConnect(RMySQL::MySQL(), dbname = dbname, host = host, 
                 user = user, password = password)

#dbExecute(con, "DELETE FROM photos")


#dbWriteTable(con, "cementtypes",CementTypes, append = TRUE, row.names = FALSE)
#dbWriteTable(con, "thinstructurecementtypes",ThinStructureCementTypes, append = TRUE, row.names = FALSE)
#dbWriteTable(con, "mineralogytypes",MineralogyTypes, append = TRUE, row.names = FALSE)
#dbWriteTable(con, "thinttructuremineralogytypes",ThinStructureMineralogyTypes, append = TRUE, row.names = FALSE)
#dbWriteTable(con, "porositytype",PorosityType, append = TRUE, row.names = FALSE)
dbWriteTable(con, "thinstructureporositytype",ThinStructurePorosityType, append = TRUE, row.names = FALSE)

# Close the connection
dbDisconnect(con) 
```


```{r}
# MySQL connection parameters
dbname <- "h762lahe056bge13"  
host <- "nnsgluut5mye50or.cbetxkdyhwsb.us-east-1.rds.amazonaws.com"  
user <- "izgrmlgwk70csp9l"  
password <- "qpmikh9t3n3a2ekg" 

# Connect to your MySQL database
con <- dbConnect(RMySQL::MySQL(), dbname = dbname, host = host, 
                 user = user, password = password)

#dbExecute(con, "DELETE FROM photos")


dbWriteTable(con, "planview",PlainView, append = TRUE, row.names = FALSE)

# Close the connection
dbDisconnect(con) 
```



